project:
  type: website

website:
  title: "Nien Xiang Tou"
  site-url: https://nienxiangtou.com
  favicon: profile.jpg
  description: "Personal blog that documents my personal projects"
  twitter-card:
    creator: "@nxrunning"
    image: "profile.jpg"
    card-style: summary_large_image
  open-graph: true
  comments:
    utterances: 
      repo: nxrunning/personalblog
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - text: Publications
        href: Publications.qmd
      - icon: twitter
        href: https://twitter.com/nxrunning
      - icon: linkedin
        href: https://www.linkedin.com/in/nien-xiang-tou-phd-a15594184/
      - icon: github
        href: https://github.com/nxrunning
format:
  html:
    theme: flatly
    css: styles.css
    highlight-style: eiffel
editor: visual

